### ISSUE TITLE
Add a link to GitHub repository

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#28]
Add a button redirecting to this repository similar to the one added in [d0b3590](https://github.com/debatecore/debate-tools/commit/d0b3590db5c83e57fb7feab4391c688bd93b1ea2).

**Comment by jakubmanczak** [comment]
This is obviously "meta" territory - or "About" territory. Probably can be grouped with general info about the site.

I was thinking a redesigned main menu could feature a summary, including mentions of things such as how the project is open source & on github. A phrasing I really like due to the clock's use in Musketeers this year is "battle-tested" – it projects confidence.

We could borrow the descending backdrop icon effect from https://debateco.re and shift the elements of the menu sideways to create a cool effect. Forgive the working sketch.

<img width="921" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/e76fb2ec-8755-4db8-a1db-1da7d03baf7d">
<img width="1912" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/965e78da-098d-4177-acdb-e353dfce58ef">

**Comment by Mateusz-Dobrzynski** [comment]
"Battle-tested" is brilliant. As for the exact placement and presentation of the GitHub link, I don't insist on anything. Creating an independent "About" section would undeniably be better but a simple icon alone would be a substantial improvement.

**Comment by jakubmanczak** [comment]
This issue is now obsolete as a link to the source code is present as of d63a0fe9992fb888947491d49508aeda6d5ebbed.
