### ISSUE TITLE
Add a PND logo

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#68]
**Acceptance Criteria**
- A logo of Poznań Debate Night is avaliable
- The name is translated to the current language (rationale: vauge acronyms are not the best option for logo selection, especially since _PND_ is very similar to more recognizable _PLD_)
  - en: Poznań Debate Night
  - pl: Poznańska Noc Debaty
  - de: Posener Debattennacht
- A mention about the logo is included in `LEGAL.md`, e.g.

```md
## Logos
- Poznań Debate Night (`path to file`) – courtesy of _Oratoria_ foundation
```

**Comment by jakubmanczak** [comment]
> The name is translated to the current language (rationale: vauge acronyms are not the best option for logo selection, especially since PND is very similar to more recognizable PLD) 

We already use acronyms for this, and I think it's a fine solution. Anyone who wishes to use a given logo knowns the exact acronym for what they're searching for anyway, and anything else doesn't matter. Besides, what use case is there for the Germans to simulate a *Poznańska Noc Debaty* branded tournament, for example? Why invest in solving problems that don't exist?

Otherwise, yeah, pop off queen.
