### ISSUE TITLE
Rename "Oxford Debate Conduction" to "Debate Clock"

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#69]
**Acceptance Criteria**
The "Oxford Debate Conduction" string in the main menu is renamed to:
- en: Oxford Debate Clock
- pl: Zegar do Debat Oksfordzkich
- de: Oxforddebattenuhr

**Comment by Mateusz-Dobrzynski** [comment]
I'm not 100% sure of the Polish translation. Any alternative must convey both parts, though: the fact that it's a clock and that it's designed for Oxford Debates.

**Comment by jakubmanczak** [comment]
I'd take this further and change it to "Advanced Debate Clock" instead.

This feeds into the idea about creating a more simplified version of the debate clock with just the debate title, joker/advocem & countdown functionality, since some seem to prefer a clock without all the bells and whistles, as proven by PLD debate marshalls (?).

**Comment by Mateusz-Dobrzynski** [comment]
1. If one doesn't like the sound effects, they can just turn it off. Problem solved. Creating a simplified version seems needless, since the current one is already quite simplistic.
2. The clock choice on PLD wasn't up to the marshalls. I talked to one who _wanted_ to use ours but couldn't. If we want to have it used during the next edition, we must contact the organizers directly.
