### ISSUE TITLE
Fix clock images

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/debate-tools#87]
**Steps to reproduce**
- Select any logo and open the console. Go to debate view
- Notice that the "Loading…" text is being displayed indefinitely and an error is thrown the console

**Remarks**
- The bug is present since [a53ea28](https://github.com/debatecore/debate-tools/commit/a53ea2824e02ff84b8edfc55000f91b5b928e352), presumably due to a packages audit that broke something

**Acceptance criteria**
- The clock images work as expected
- If Playwright is set up (see #79), the logos functionality is covered with an e2e test

**Comment by jakubmanczak** [comment]
> Notice that the "Loading…" text is being displayed indefinitely and an error is thrown the console

No error is thrown on Chrome based browsers for me. That tracks with the following:

It's not the image being broken, but the way we decide to show them. As seen below, simply commenting out the code that hides the element while it's loading is enough for it to show.

<img width="1012" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/bd0aa5f8-1274-48a7-8dde-8afbab796f90">
<img width="516" alt="image" src="https://github.com/debatecore/debate-tools/assets/56172798/1b437a8a-8da0-4f96-9879-38b422dd4e59">

**Comment by jakubmanczak** [comment]
After a bit of testing, it is my educated guess that the onLoad callback doesn't actually fire if the image element isn't rendered.

You can force it to work by commenting out the `hidden={}` line (no. 49) and adding it back - since it rendered and is now presumably kept in memory or cache, the onLoad fires even after navigating to config view and back. If you refresh though, it stops working again. This happens no matter if we use `hidden={}`, the `hidden` class or conditionally avoid rendering it.

This **doesn't (!)** happen if you apply `opacity-0` instead of hiding it – since it renders the element anyway, and thus onLoad can fire.

Looking at the node-modules diff for a53ea2824e02ff84b8edfc55000f91b5b928e352 as well as package.json, we permitted a minor version increment of 14.1.0 to 14.2.4, where this behavior could've changed as some kind of optimisation.

**Comment by jakubmanczak** [comment]
> Looking at the node-modules diff for https://github.com/debatecore/debate-tools/commit/a53ea2824e02ff84b8edfc55000f91b5b928e352 as well as package.json, we permitted a nextjs minor version increment of 14.1.0 to 14.2.4, where this behavior could've changed as some kind of optimisation.

This seems to have been a wrong assumption – downgrading explicitly back to next 14.1 or even 14.0 doesn't bring back old behavior.

Nevertheless, turning down the opacity instead of hiding the image seems to fix the issue.
